# This is a basic workflow to help you get started with Actions

name: file-packaging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:
    - '*'
jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Listing the contents
      run: |
        ls
        
    - name: Archive Release 2
      uses: papeloto/action-zip@v1
      with:
        files: Test-zip/
        recursive: true
        dest: StorOne-ManagedApplication.zip
        
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "StorOne-ManagedApplication.zip"
        tag: "zippper"
        replacesArtifacts: "true"
        allowUpdates: "true"
        token: ${{ secrets.GITHUB_TOKEN }}
